name: 'Run Node Script'
description: 'Setup Node, install dependencies if needed, and run a Node script'

runs:
  using: 'composite'
  steps:
    - name: Run Node script
      run: node "${{ github.action_path }}/index.js" "${{ toJSON(github.event.pull_request.body) }}"
      shell: bash
